[project]
authors = ["Kanoopz"]
entry = "main.sw"
license = "Apache-2.0"
name = "publicationSmartContract"

[dependencies]
nftInterface = { path = "../../interfaces/nftInterface" }
publicationInterface = { path = "../../interfaces/publicationInterface" }
