/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { JERICHOAbi } from "./JERICHOAbi";

export { JERICHOAbi__factory } from "./factories/JERICHOAbi__factory";
