/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

interface JERICHOAbiInterface extends Interface {
  functions: {
    test_function: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "test_function",
    values?: undefined
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "test_function",
    data: BytesLike
  ): DecodedValue;
}

export class JERICHOAbi extends Contract {
  interface: JERICHOAbiInterface;
  functions: {
    test_function: InvokeFunction<[], boolean>;
  };
}
