[project]
authors = ["Kanoopz"]
entry = "main.sw"
license = "Apache-2.0"
name = "mainSmartContract"

[dependencies]
mainInterface = { path = "../../interfaces/mainInterface" }
nftInterface = { path = "../../interfaces/nftInterface" }
publicationInterface = { path = "../../interfaces/publicationInterface" }
